name: Java CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build, Test & Coverage
      run: mvn clean verify

    - name: SonarCloud Scan
      run: mvn sonar:sonar \
        -Dsonar.projectKey=sanikashidore_Web-Crawler-Deploy \
        -Dsonar.organization=sanikashidore \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \    
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

    - name: SonarCloud Scan
      run: mvn sonar:sonar -Dsonar.projectKey=sanikashidore_Web-Crawler-Deploy -Dsonar.organization=sanikashidore -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Build Docker Image
      run: docker build -t research-crawler-img .